In [2]:
import pandas as pd

In [3]:
mortality_df = pd.read_csv('original-data/mort.csv')

# Drop rows with NaN FIPS ID
mortality_df = mortality_df.dropna(subset=['FIPS'])
mortality_df['FIPS'] = mortality_df['FIPS'].astype(int)

mortality_df.head()

,Location,FIPS,Category,"Mortality Rate, 1980*","Mortality Rate, 1980* (Min)","Mortality Rate, 1980* (Max)","Mortality Rate, 1985*","Mortality Rate, 1985* (Min)","Mortality Rate, 1985* (Max)","Mortality Rate, 1990*",...,"Mortality Rate, 2005* (Max)","Mortality Rate, 2010*","Mortality Rate, 2010* (Min)","Mortality Rate, 2010* (Max)","Mortality Rate, 2014*","Mortality Rate, 2014* (Min)","Mortality Rate, 2014* (Max)","% Change in Mortality Rate, 1980-2014","% Change in Mortality Rate, 1980-2014 (Min)","% Change in Mortality Rate, 1980-2014 (Max)"
1,Alabama,1,Neonatal disorders,11.03,10.57,12.00,8.51,8.25,9.12,7.52,...,6.52,5.58,5.16,5.78,5.10,4.67,5.32,-53.82,-60.08,-50.77
2,"Autauga County, Alabama",1001,Neonatal disorders,9.58,8.37,11.02,7.50,6.56,8.58,6.76,...,6.30,4.83,4.19,5.49,4.56,3.96,5.21,-52.43,-60.01,-46.16
3,"Baldwin County, Alabama",1003,Neonatal disorders,8.75,7.86,9.81,6.54,5.88,7.27,5.76,...,5.03,4.02,3.53,4.48,3.68,3.25,4.08,-57.97,-64.96,-52.87
4,"Barbour County, Alabama",1005,Neonatal disorders,12.30,10.64,14.15,9.26,8.13,10.60,8.12,...,7.89,5.99,5.16,6.84,5.43,4.63,6.24,-55.86,-62.49,-50.32
5,"Bibb County, Alabama",1007,Neonatal disorders,11.28,9.63,13.14,8.88,7.57,10.27,7.92,...,8.26,6.29,5.32,7.27,5.89,4.98,6.85,-47.76,-56.13,-40.11

In [4]:
aqi_df = pd.read_excel('original-data/ctyfactbook2023.xlsx', sheet_name='County Factbook 2023', skiprows=2)

# Drop rows with NaN FIPS ID
aqi_df = aqi_df.dropna(subset=['County FIPS Code'])
aqi_df['County FIPS Code'] = aqi_df['County FIPS Code'].astype(int)

aqi_df

,State,County,County FIPS Code,2010 Population,CO 8-hr (ppm),Pb 3-mo (Âµg/m3),NO2 AM (ppb),NO2 1-hr (ppb),O3 8-hr (ppm),PM10 24-hr (Âµg/m3),PM2.5 Wtd AM (Âµg/m3),PM2.5 24-hr (Âµg/m3),SO2 1-hr (ppb)
0,Alabama,Baldwin County,1003,182265.0,ND,ND,ND,ND,0.065,ND,7.6,18,ND
1,Alabama,Clay County,1027,13932.0,ND,ND,ND,ND,ND,ND,IN,IN,ND
2,Alabama,Colbert County,1033,54428.0,ND,ND,ND,ND,ND,ND,IN,IN,ND
3,Alabama,DeKalb County,1049,71109.0,ND,ND,ND,ND,0.066,ND,8.9,21,ND
4,Alabama,Elmore County,1051,79303.0,ND,ND,ND,ND,0.061,ND,ND,ND,ND
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1140,Puerto Rico,"Lares Municipio, Puerto Rico",72081,30753.0,ND,ND,ND,ND,ND,ND,IN,IN,ND
1141,Puerto Rico,"MayagÃ¼ez Municipio, Puerto Rico",72097,89080.0,ND,ND,ND,ND,0.043,ND,IN,IN,ND
1142,Puerto Rico,"Ponce Municipio, Puerto Rico",72113,166327.0,10,ND,ND,ND,ND,109,IN,IN,ND
1143,Puerto Rico,"Salinas Municipio, Puerto Rico",72123,31078.0,ND,ND,ND,ND,ND,ND,ND,ND,IN
1144,Puerto Rico,"San Juan Municipio, Puerto Rico",72127,395326.0,ND,ND,ND,ND,ND,ND,IN,IN,ND

In [5]:
merged_df = pd.merge(mortality_df, aqi_df, left_on='FIPS', right_on='County FIPS Code', how='inner')

merged_df

,Location,FIPS,Category,"Mortality Rate, 1980*","Mortality Rate, 1980* (Min)","Mortality Rate, 1980* (Max)","Mortality Rate, 1985*","Mortality Rate, 1985* (Min)","Mortality Rate, 1985* (Max)","Mortality Rate, 1990*",...,2010 Population,CO 8-hr (ppm),Pb 3-mo (Âµg/m3),NO2 AM (ppb),NO2 1-hr (ppb),O3 8-hr (ppm),PM10 24-hr (Âµg/m3),PM2.5 Wtd AM (Âµg/m3),PM2.5 24-hr (Âµg/m3),SO2 1-hr (ppb)
0,"Baldwin County, Alabama",1003,Neonatal disorders,8.75,7.86,9.81,6.54,5.88,7.27,5.76,...,182265.0,ND,ND,ND,ND,0.065,ND,7.6,18,ND
1,"Baldwin County, Alabama",1003,HIV/AIDS and tuberculosis,0.84,0.63,1.12,1.44,1.18,1.75,6.51,...,182265.0,ND,ND,ND,ND,0.065,ND,7.6,18,ND
2,"Baldwin County, Alabama",1003,Musculoskeletal disorders,2.80,2.23,3.50,2.81,2.29,3.45,2.99,...,182265.0,ND,ND,ND,ND,0.065,ND,7.6,18,ND
3,"Baldwin County, Alabama",1003,"Diabetes, urogenital, blood, and endocrine dis...",46.30,43.40,49.00,44.87,42.60,47.33,46.33,...,182265.0,ND,ND,ND,ND,0.065,ND,7.6,18,ND
4,"Baldwin County, Alabama",1003,Digestive diseases,19.34,17.96,20.87,18.24,17.07,19.57,17.32,...,182265.0,ND,ND,ND,ND,0.065,ND,7.6,18,ND
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23704,"Weston County, Wyoming",56045,Other non-communicable diseases,10.45,8.65,12.27,9.61,8.14,11.10,9.10,...,7208.0,ND,ND,ND,ND,0.062,ND,IN,IN,3
23705,"Weston County, Wyoming",56045,Self-harm and interpersonal violence,24.89,21.79,28.23,24.61,21.79,27.71,25.38,...,7208.0,ND,ND,ND,ND,0.062,ND,IN,IN,3
23706,"Weston County, Wyoming",56045,Neoplasms,244.28,223.86,265.39,236.23,218.00,254.46,231.15,...,7208.0,ND,ND,ND,ND,0.062,ND,IN,IN,3
23707,"Weston County, Wyoming",56045,Transport injuries,46.91,42.63,51.92,39.05,35.83,42.78,37.36,...,7208.0,ND,ND,ND,ND,0.062,ND,IN,IN,3
23708,"Weston County, Wyoming",56045,Neglected tropical diseases and malaria,0.08,0.05,0.13,0.08,0.05,0.13,0.07,...,7208.0,ND,ND,ND,ND,0.062,ND,IN,IN,3

In [12]:
drop_columns = [
    'Location',
    'County FIPS Code',
    'State',
    'County',
    'Mortality Rate, 1980* (Min)',
    'Mortality Rate, 1980* (Max)',
    'Mortality Rate, 1985* (Min)',
    'Mortality Rate, 1985* (Max)',
    'Mortality Rate, 1990* (Min)',
    'Mortality Rate, 1990* (Max)',
    'Mortality Rate, 1995* (Min)',
    'Mortality Rate, 1995* (Max)',
    'Mortality Rate, 2000* (Min)',
    'Mortality Rate, 2000* (Max)',
    'Mortality Rate, 2005* (Min)',
    'Mortality Rate, 2005* (Max)',
    'Mortality Rate, 2010* (Min)',
    'Mortality Rate, 2010* (Max)',
    'Mortality Rate, 2014* (Min)',
    'Mortality Rate, 2014* (Max)',
    '% Change in Mortality Rate, 1980-2014',
    '% Change in Mortality Rate, 1980-2014 (Min)',
    '% Change in Mortality Rate, 1980-2014 (Max)'
]

trimmed_df = merged_df.drop(drop_columns, axis=1)

trimmed_df = trimmed_df.rename(columns={
    "CO          8-hr (ppm)": "CO 8-hr (ppm)",
    "Pb           3-mo (Âµg/m3)": "Pb 3-mo (mu g/m3)",
    "NO2         AM (ppb)": "NO2 AM (ppb)",
    "NO2          1-hr (ppb)": "NO2 1-hr (ppb)",
    "O3            8-hr (ppm)": "O3 8-hr (ppm)",
    "PM10        24-hr (Âµg/m3) ": "PM10 24-hr (mu g/m3)",
    "PM2.5     Wtd AM (Âµg/m3) ": "PM2.5 Wtd AM (mu g/m3)",
    "PM2.5     24-hr (Âµg/m3) ": "PM2.5 24-hr (mu g/m3)",
    "SO2         1-hr (ppb)": "SO2 1-hr (ppb)"
})

print(trimmed_df.columns.tolist())
trimmed_df

['FIPS', 'Category', 'Mortality Rate, 1980*', 'Mortality Rate, 1985*', 'Mortality Rate, 1990*', 'Mortality Rate, 1995*', 'Mortality Rate, 2000*', 'Mortality Rate, 2005*', 'Mortality Rate, 2010*', 'Mortality Rate, 2014*', '2010 Population', 'CO 8-hr (ppm)', 'Pb 3-mo (mu g/m3)', 'NO2 AM (ppb)', 'NO2 1-hr (ppb)', 'O3 8-hr (ppm)', 'PM10 24-hr (mu g/m3)', 'PM2.5 Wtd AM (mu g/m3)', 'PM2.5 24-hr (mu g/m3)', 'SO2 1-hr (ppb)']

,FIPS,Category,"Mortality Rate, 1980*","Mortality Rate, 1985*","Mortality Rate, 1990*","Mortality Rate, 1995*","Mortality Rate, 2000*","Mortality Rate, 2005*","Mortality Rate, 2010*","Mortality Rate, 2014*",2010 Population,CO 8-hr (ppm),Pb 3-mo (mu g/m3),NO2 AM (ppb),NO2 1-hr (ppb),O3 8-hr (ppm),PM10 24-hr (mu g/m3),PM2.5 Wtd AM (mu g/m3),PM2.5 24-hr (mu g/m3),SO2 1-hr (ppb)
0,1003,Neonatal disorders,8.75,6.54,5.76,4.65,4.56,4.55,4.02,3.68,182265.0,ND,ND,ND,ND,0.065,ND,7.6,18,ND
1,1003,HIV/AIDS and tuberculosis,0.84,1.44,6.51,11.18,3.82,3.18,2.27,2.01,182265.0,ND,ND,ND,ND,0.065,ND,7.6,18,ND
2,1003,Musculoskeletal disorders,2.80,2.81,2.99,3.24,3.45,3.33,2.98,2.98,182265.0,ND,ND,ND,ND,0.065,ND,7.6,18,ND
3,1003,"Diabetes, urogenital, blood, and endocrine dis...",46.30,44.87,46.33,50.03,52.70,51.59,50.44,49.57,182265.0,ND,ND,ND,ND,0.065,ND,7.6,18,ND
4,1003,Digestive diseases,19.34,18.24,17.32,16.74,15.70,14.70,13.88,13.32,182265.0,ND,ND,ND,ND,0.065,ND,7.6,18,ND
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23704,56045,Other non-communicable diseases,10.45,9.61,9.10,8.14,7.54,7.52,6.92,7.06,7208.0,ND,ND,ND,ND,0.062,ND,IN,IN,3
23705,56045,Self-harm and interpersonal violence,24.89,24.61,25.38,25.59,23.42,25.00,26.05,27.02,7208.0,ND,ND,ND,ND,0.062,ND,IN,IN,3
23706,56045,Neoplasms,244.28,236.23,231.15,234.09,222.62,217.02,202.60,205.54,7208.0,ND,ND,ND,ND,0.062,ND,IN,IN,3
23707,56045,Transport injuries,46.91,39.05,37.36,35.02,33.13,32.32,27.12,26.18,7208.0,ND,ND,ND,ND,0.062,ND,IN,IN,3
23708,56045,Neglected tropical diseases and malaria,0.08,0.08,0.07,0.07,0.09,0.19,0.18,0.21,7208.0,ND,ND,ND,ND,0.062,ND,IN,IN,3

In [ ]:
# merged_df.to_csv('merged-data/air_quality_mortality.csv', index=False)
trimmed_df.to_csv('merged-data/air_quality_mortality_trimmed.csv', index=False)

## Aggregate Data by Metropolitan Area

In [ ]:
cbsa_crosswalk = pd.read_csv('original-data/cbsa2fipsxw.csv', dtype={'fipsstatecode': str, 'fipscountycode': str})
cbsa_crosswalk['FIPS'] = cbsa_crosswalk['fipsstatecode'].astype(str) + cbsa_crosswalk['fipscountycode'].astype(str)
cbsa_crosswalk['FIPS'] = cbsa_crosswalk['FIPS'].astype(int)
cbsa_crosswalk.head()

,cbsacode,metropolitandivisioncode,csacode,cbsatitle,metropolitanmicropolitanstatis,metropolitandivisiontitle,csatitle,countycountyequivalent,statename,fipsstatecode,fipscountycode,centraloutlyingcounty,FIPS
0,33860,NaN,388.0,"Montgomery, AL",Metropolitan Statistical Area,NaN,"Montgomery-Selma, AL",Autauga County,Alabama,01,001,Central,1001
1,19300,NaN,380.0,"Daphne-Fairhope-Foley, AL",Metropolitan Statistical Area,NaN,"Mobile-Daphne-Fairhope, AL",Baldwin County,Alabama,01,003,Central,1003
2,21640,NaN,NaN,"Eufaula, AL-GA",Micropolitan Statistical Area,NaN,NaN,Barbour County,Alabama,01,005,Central,1005
3,13820,NaN,142.0,"Birmingham, AL",Metropolitan Statistical Area,NaN,"Birmingham-Cullman-Talladega, AL",Bibb County,Alabama,01,007,Outlying,1007
4,13820,NaN,142.0,"Birmingham, AL",Metropolitan Statistical Area,NaN,"Birmingham-Cullman-Talladega, AL",Blount County,Alabama,01,009,Outlying,1009

In [ ]:
metro_df = trimmed_df.merge(cbsa_crosswalk, on="FIPS", how="left")

manual_agg = {
    "2010 Population": "sum"
}

ignore_list = [
    "FIPS",
    "Category"
]

categorical_columns = ['FIPS', 'cbsacode', 'csacode', 'cbsatitle', 'csatitle']
metro_df[categorical_columns] = metro_df[categorical_columns].astype('category')

# Add a default aggregation method (e.g., "max") for all other columns
default_agg = {col: "mean" for col in metro_df.columns if col not in manual_agg and col not in ignore_list}
agg_methods = {**manual_agg, **default_agg}

# Group by MetroArea and Category
aggregated_data = metro_df.groupby(["cbsacode", "Category"]).agg(agg_methods).reset_index()
aggregated_data

In [8]:
demographic_df = pd.read_csv('original-data/raw_data.csv')
demographic_df.head()

,FIPS,County,State,Medicare Beneficiaries with CKD Percentage,Population,Percent Age 0-29,Percent Age 30-59,Percent Age 60+,Percent Male,Percent White,...,Avg Annual Temperature,Annual Precipitation,"HIV Prevalence (per 100,000)",Diabetes Percentage,Adult Smoking Percentage,Excessive Drinking Percentage,Food Insecurity Percentage,Enrolled in Medicare,Population Density,Reported CKD Prevalence (%)
0,1001,Autauga,Alabama,22.35,55869,0.379978,0.399971,0.220050,0.484920,0.779735,...,66.525,51.28,222.0,11.0,20.0,16.0,16.0,11059.0,92.440187,4.424075
1,1003,Baldwin,Alabama,21.21,223234,0.340347,0.377537,0.282117,0.484904,0.891903,...,68.750,61.11,173.0,9.0,20.0,22.0,13.0,53490.0,110.131872,5.082214
2,1005,Barbour,Alabama,23.53,24686,0.359191,0.381512,0.259297,0.529207,0.501499,...,66.850,43.67,498.0,17.0,28.0,14.0,21.0,6152.0,27.293332,5.863913
3,1007,Bibb,Alabama,37.21,22394,0.359516,0.411717,0.228767,0.532687,0.777887,...,64.700,56.40,208.0,13.0,25.0,16.0,16.0,4713.0,35.752032,7.831148
4,1009,Blount,Alabama,31.03,57826,0.368433,0.381264,0.250303,0.492374,0.971310,...,63.325,67.61,72.0,11.0,22.0,16.0,15.0,13044.0,88.876935,6.999539

In [13]:
merged_df2 = pd.merge(trimmed_df, demographic_df, left_on='FIPS', right_on='FIPS', how='inner')
merged_df2

,FIPS,Category,"Mortality Rate, 1980*","Mortality Rate, 1985*","Mortality Rate, 1990*","Mortality Rate, 1995*","Mortality Rate, 2000*","Mortality Rate, 2005*","Mortality Rate, 2010*","Mortality Rate, 2014*",...,Avg Annual Temperature,Annual Precipitation,"HIV Prevalence (per 100,000)",Diabetes Percentage,Adult Smoking Percentage,Excessive Drinking Percentage,Food Insecurity Percentage,Enrolled in Medicare,Population Density,Reported CKD Prevalence (%)
0,1003,Neonatal disorders,8.75,6.54,5.76,4.65,4.56,4.55,4.02,3.68,...,68.75,61.11,173.000,9.0,20.0,22.0,13.0,53490.0,110.131872,5.082214
1,1003,HIV/AIDS and tuberculosis,0.84,1.44,6.51,11.18,3.82,3.18,2.27,2.01,...,68.75,61.11,173.000,9.0,20.0,22.0,13.0,53490.0,110.131872,5.082214
2,1003,Musculoskeletal disorders,2.80,2.81,2.99,3.24,3.45,3.33,2.98,2.98,...,68.75,61.11,173.000,9.0,20.0,22.0,13.0,53490.0,110.131872,5.082214
3,1003,"Diabetes, urogenital, blood, and endocrine dis...",46.30,44.87,46.33,50.03,52.70,51.59,50.44,49.57,...,68.75,61.11,173.000,9.0,20.0,22.0,13.0,53490.0,110.131872,5.082214
4,1003,Digestive diseases,19.34,18.24,17.32,16.74,15.70,14.70,13.88,13.32,...,68.75,61.11,173.000,9.0,20.0,22.0,13.0,53490.0,110.131872,5.082214
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23452,56045,Other non-communicable diseases,10.45,9.61,9.10,8.14,7.54,7.52,6.92,7.06,...,41.65,20.19,54.125,8.0,19.0,19.0,12.0,1629.0,2.887537,3.083036
23453,56045,Self-harm and interpersonal violence,24.89,24.61,25.38,25.59,23.42,25.00,26.05,27.02,...,41.65,20.19,54.125,8.0,19.0,19.0,12.0,1629.0,2.887537,3.083036
23454,56045,Neoplasms,244.28,236.23,231.15,234.09,222.62,217.02,202.60,205.54,...,41.65,20.19,54.125,8.0,19.0,19.0,12.0,1629.0,2.887537,3.083036
23455,56045,Transport injuries,46.91,39.05,37.36,35.02,33.13,32.32,27.12,26.18,...,41.65,20.19,54.125,8.0,19.0,19.0,12.0,1629.0,2.887537,3.083036
23456,56045,Neglected tropical diseases and malaria,0.08,0.08,0.07,0.07,0.09,0.19,0.18,0.21,...,41.65,20.19,54.125,8.0,19.0,19.0,12.0,1629.0,2.887537,3.083036

In [14]:
merged_df2.to_csv('merged-data/aqi_demographic.csv', index=False)